name: Build and deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build 🏗️
        env:
          MY_EMAIL: lukas.tietenberg@outlook.de
          MY_NAME: sourcefranke
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_SECRET }}@github.com/$MY_NAME/dice-roll-calculator.git
          npm run build

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
